{ config
, ...
}: {

  home.file.".config/hypr/idle.sh".source = ./idle.sh;

  wayland.windowManager.hyprland.extraConfig = ''
    ########################################################################################
      AUTOGENERATED HYPR CONFIG.
      PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
      OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
    ########################################################################################

    #
    # Please note not all available settings / options are set here.
    # For a full list, see the wiki
    #

    # autogenerated = 1 # remove this line to remove the warning

    # Execute your favorite apps at launch
    # exec-once = waybar & hyprpaper & firefox
    exec-once = waybar & firefox & mpvpaper -o "no-audio loop" "*" /media/big/LightShot/bg/BGs/bg.webm
    exec-once = dbus-hyprland-environment
    exec-once = systemctl --user start graphical-session.target

    # swaylock gives a white background,
    # and ruins workspaces on multiple monitors,
    # so it's kinda annoying
    # exec-once = ~/.config/hypr/idle.sh

    # See https://wiki.hyprland.org/Configuring/Monitors/
    monitor = DP-1,1920x1080@144,1920x0,1
    monitor = DP-2,1920x1080@144,3840x0,1
    monitor = HDMI-A-1,1920x1080@60,0x0,1

    workspace = DP-1, 1
    workspace = DP-1, 2
    #workspace = DP-2, 3
    #workspace = HDMI-A-1, 4
    wsbind = 1, DP-1
    wsbind = 2, DP-1
    wsbind = 3, DP-2
    wsbind = 4, DP-2
    wsbind = 5, HDMI-A-1

    # See https://wiki.hyprland.org/Configuring/Keywords/ for more

    # Source a file (multi-file configs)
    # source = ~/.config/hypr/myColors.conf

    # Some default env vars.
    env = XCURSOR_SIZE,24

    # For all categories, see https://wiki.hyprland.org/Configuring/Variables/
    input {
        kb_layout = us,ar
        kb_variant =
        kb_model =
        kb_options = grp:alt_shift_toggle
        kb_rules =
        numlock_by_default = true

        follow_mouse = 1

        touchpad {
            natural_scroll = no
        }

        sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    }

    general {
        # See https://wiki.hyprland.org/Configuring/Variables/ for more

        gaps_in = 5
        gaps_out = 10
        border_size = 2
        col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
        col.inactive_border = rgba(595959aa)

        # layout = dwindle
        layout = master
    }

    decoration {
        # See https://wiki.hyprland.org/Configuring/Variables/ for more

        rounding = 7
        blur = yes
        blur_size = 3
        blur_passes = 1
        blur_new_optimizations = on

        drop_shadow = yes
        shadow_range = 4
        shadow_render_power = 3
        col.shadow = rgba(1a1a1aee)
    }

    animations {
        enabled = yes

        # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

        bezier = myBezier, 0.05, 0.9, 0.1, 1.05

        animation = windows, 1, 7, myBezier
        animation = windowsOut, 1, 7, default, popin 80%
        animation = border, 1, 10, default
        animation = borderangle, 1, 8, default
        animation = fade, 1, 7, default
        animation = workspaces, 1, 6, default
    }

    dwindle {
        # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
        pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        preserve_split = yes # you probably want this
    }

    master {
        # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
        new_is_master = false
    }

    gestures {
        # See https://wiki.hyprland.org/Configuring/Variables/ for more
        workspace_swipe = off
    }

    # Example per-device config
    # See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
    device:epic-mouse-v1 {
        sensitivity = -0.5
    }

    # Example windowrule v1
    # windowrule = float, ^(kitty)$
    # Example windowrule v2
    # windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
    # See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

    windowrule=float,org.kde.polkit-kde-authentication-agent-1

    # See https://wiki.hyprland.org/Configuring/Keywords/ for more
    $mainMod = SUPER

    # Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
    bind = $mainMod, Q, exec, kitty
    bind = $mainMod, C, killactive,
    bind = $mainMod, M, exit,
    bind = $mainMod, E, exec, dolphin
    bind = $mainMod, V, togglefloating,
    bind = $mainMod, R, layoutmsg, orientationnext
    bind = $mainMod, D, exec, pkill rofi || ~/.config/rofi/launcher.sh
    bind = $mainMod, P, pseudo, # dwindle
    bind = $mainMod, J, togglesplit, # dwindle
    bind = , code:107, exec, IMG=~/Pictures/$(date +%Y-%m-%d_%H-%m-%s).png && grim -g "$(slurp)" $IMG && wl-copy < $IMG

    # Move focus with mainMod + arrow keys
    bind = $mainMod, left, movefocus, l
    bind = $mainMod, right, movefocus, r
    bind = $mainMod, up, movefocus, u
    bind = $mainMod, down, movefocus, d

    # Switch workspaces with mainMod + [0-9]
    bind = $mainMod, 1, workspace, 1
    bind = $mainMod, 2, workspace, 2
    bind = $mainMod, 3, workspace, 3
    bind = $mainMod, 4, workspace, 4
    bind = $mainMod, 5, workspace, 5
    bind = $mainMod, 6, workspace, 6
    bind = $mainMod, 7, workspace, 7
    bind = $mainMod, 8, workspace, 8
    bind = $mainMod, 9, workspace, 9
    bind = $mainMod, 0, workspace, 10

    # Move active window to a workspace with mainMod + SHIFT + [0-9]
    bind = $mainMod SHIFT, 1, movetoworkspace, 1
    bind = $mainMod SHIFT, 2, movetoworkspace, 2
    bind = $mainMod SHIFT, 3, movetoworkspace, 3
    bind = $mainMod SHIFT, 4, movetoworkspace, 4
    bind = $mainMod SHIFT, 5, movetoworkspace, 5
    bind = $mainMod SHIFT, 6, movetoworkspace, 6
    bind = $mainMod SHIFT, 7, movetoworkspace, 7
    bind = $mainMod SHIFT, 8, movetoworkspace, 8
    bind = $mainMod SHIFT, 9, movetoworkspace, 9
    bind = $mainMod SHIFT, 0, movetoworkspace, 10

    # Scroll through existing workspaces with mainMod + scroll
    bind = $mainMod, mouse_down, workspace, e+1
    bind = $mainMod, mouse_up, workspace, e-1

    # Move/resize windows with mainMod + LMB/RMB and dragging
    bindm = $mainMod, mouse:272, movewindow
    bindm = $mainMod, mouse:273, resizewindow

    bindm = $mainMod, mouse:282, resizewindow

    # Resize active window with keyboard
    binde = $mainMod CTRL, L, resizeactive, 45 0
    binde = $mainMod CTRL, H, resizeactive, -45 0
    binde = $mainMod CTRL, K, resizeactive, 0 -45
    binde = $mainMod CTRL, H, resizeactive, 0 45

    bind = $mainMod, F, fullscreen, 1
    bind = $mainMod CTRL, F, fullscreen, 0

    bind = $mainMod, RETURN, layoutmsg, swapwithmaster
    bind = $mainMod, KP_ENTER, layoutmsg, swapwithmaster

    # Multimedia binds
    # Play-Pause button
    bind = , code:172, exec, playerctl play-pause
    # forward button
    bind = , code:171, exec, playerctl next
    # backward button
    bind = , code:173, exec, playerctl previous
    # Mute button
    bind = , code:121, exec, pamixer -t
    # Raise Spotify Volume
    bind = , code:123, exec, playerctl --player=spotify volume 0.05+
    # Lower Spotify Volume
    bind = , code:122, exec, playerctl --player=spotify volume 0.05-

    # Global hotkeys
    # bind = SUPER,F10,pass,^(com\.obsproject\.Studio)$
    # bind = ,F8,pass,^(Discord)$
    # bind = ,F7,pass,^(Discord)$

    # League of legends
    windowrulev2 = float, class:^(leagueclientux.exe)$,title:^(League of Legends)$

    windowrule = size 1280 720,^(leagueclientux.exe)$
    
    windowrule = center,^(leagueclientux.exe)$

    windowrulev2 = size 1920 1080,class:^ (league of legends.exe)$

    windowrulev2 = fullscreen,class:^(league of legends.exe)$

    windowrule = forceinput,^(league of legends.exe)$

    windowrulev2 = float, class:^(firefox)$,title:^(Sharing Indicator)$
  '';
}
