#!/usr/bin/env bash
set -e
pushd ~/nixos_config/
alejandra . &> /dev/null
git dft *.nix
echo "Rebuilding NixOS..."
sudo nixos-rebuild switch --flake .# &>nixos-switch.log || (cat "nixos-switch.log" | grep --color error && false)
gen=$(nixos-rebuild list-generations | grep current)
git commit -am "$gen"
popd
