theme = "onedark"

[keys.insert]

"C-[" = "normal_mode"
"C-c" = "normal_mode"
"A-ret" = "open_below"
"C-s" = "goto_first_nonwhitespace"
"C-e" = ["goto_line_end", "move_char_right"]
"C-a" = "goto_line_start"

[keys.select]

"C-s" = ":w"
"C-[" = "normal_mode"
"C-c" = "normal_mode"
r = ["replace", "normal_mode"]
R = ["replace_with_yanked", "normal_mode"]
"x" = "extend_to_line_bounds"
"X" = "extend_line_below"

[keys.normal]

# unholy stuff
e = ["move_next_word_end", "collapse_selection"]
E = ["move_next_long_word_end", "collapse_selection"]
w = ["move_next_word_start", "collapse_selection"]
W = ["move_next_long_word_start", "collapse_selection"]
b = ["move_prev_word_start", "collapse_selection"]
B = ["move_prev_long_word_start", "collapse_selection"]

t = ["find_till_char", "collapse_selection"]
T = ["till_prev_char", "collapse_selection"]

f = ["find_next_char", "collapse_selection"]
F = ["find_prev_char", "collapse_selection"]
# end of unholy stuff

# "A-s" = "move_line_down" # Maps the 'a' key to the move_char_left command
C-f = [":new", ":insert-output lf-pick", ":theme default", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme onedark"] # tokyonight_storm
"C-l" = ":lsp-restart"
"C-s" = ":w"
# "C-o" = ":config-open"
"ret" = ["add_newline_below"]
"S-ret" = ["add_newline_above"]
"C-d" = ["half_page_down", "align_view_center"]
"C-u" = ["half_page_up", "align_view_center"]
"C-up" = ["extend_to_line_bounds", "search_selection", "delete_selection", "move_line_up", "paste_before", "move_line_up", "goto_line_end", "search_next"]
"C-down" = ["extend_to_line_bounds", "search_selection", "delete_selection", "move_line_down", "paste_before", "move_line_up", "goto_line_end", "search_next"]
"x" = "extend_to_line_bounds"
"X" = "extend_line_below"
esc = ["collapse_selection", "keep_primary_selection"]
"C-v" = ":insert-output"
"C-I" = ":toggle lsp.display-inlay-hints"

[keys.normal.space]

R = ["replace_selections_with_clipboard", "normal_mode"]
Y = "yank_main_selection_to_clipboard"
u = ":sh arduino-cli compile && arduino-cli upload"

[editor.cursor-shape]

insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]

space = "all"

[editor.lsp]

display-messages = true

[editor.statusline]
right = ["version-control", "diagnostics", "selections", "position", "file-encoding"]

[editor]

line-number = "relative"
bufferline = "multiple"

[editor.file-picker]
hidden = false
git-ignore = true