theme = "onedark"

[keys.insert]

"C-[" = "normal_mode"
"C-c" = "normal_mode"
"A-ret" = "open_below"
"C-s" = "goto_first_nonwhitespace"
"C-e" = ["goto_line_end", "move_char_right"]
"C-a" = "goto_line_start"

[keys.select]

"C-s" = ":w"
"C-[" = "normal_mode"
"C-c" = "normal_mode"
r = ["replace", "normal_mode"]
R = ["replace_with_yanked", "normal_mode"]
"x" = "extend_to_line_bounds"
"X" = "extend_line_below"

[keys.normal]

# unholy stuff
e = ["move_next_word_end", "collapse_selection"]
E = ["move_next_long_word_end", "collapse_selection"]
w = ["move_next_word_start", "collapse_selection"]
W = ["move_next_long_word_start", "collapse_selection"]
b = ["move_prev_word_start", "collapse_selection"]
B = ["move_prev_long_word_start", "collapse_selection"]

t = ["find_till_char", "collapse_selection"]
T = ["till_prev_char", "collapse_selection"]

f = ["find_next_char", "collapse_selection"]
F = ["find_prev_char", "collapse_selection"]
# end of unholy stuff

# "A-s" = "move_line_down" # Maps the 'a' key to the move_char_left command
"C-l" = ":lsp-restart"
"C-s" = ":w"
# "C-o" = ":config-open"
"ret" = ["add_newline_below"]
"S-ret" = ["add_newline_above"]
"C-d" = ["page_cursor_half_down", "align_view_center"]
"C-u" = ["page_cursor_half_up", "align_view_center"]
"C-up" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"C-down" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"x" = "extend_to_line_bounds"
"X" = "extend_line_below"
esc = ["collapse_selection", "keep_primary_selection"]
"C-I" = ":toggle-option lsp.display-inlay-hints"
"," = "repeat_last_motion"

[keys.normal.space]

R = ["replace_selections_with_clipboard", "normal_mode"]
Y = "yank_main_selection_to_clipboard"
u = ":sh arduino-cli compile && arduino-cli upload"

[editor.cursor-shape]

insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]

space = "all"

[editor.lsp]

display-messages = true

[editor.statusline]
right = ["version-control", "diagnostics", "selections", "position", "file-encoding"]

[editor]
line-number = "relative"
bufferline = "multiple"

# Minimum severity to show a diagnostic after the end of a line:
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
# Minimum severity to show a diagnostic on the primary cursor's line.
# Note that `cursor-line` diagnostics are hidden in insert mode.
cursor-line = "error"
# Minimum severity to show a diagnostic on other lines:
# other-lines = "error"

[editor.file-picker]
hidden = false
git-ignore = true
