[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
# auto-format = false

[language-server.rust-analyzer]
command = "rust-analyzer"
environment = { "CARGO_TARGET_DIR" = "target/analyzer" }

[language.debugger]
command = "codelldb"
name = "codelldb"
port-arg = "--port {}"
transport = "tcp"

[[language.debugger.templates]]
name = "binary"
request = "launch"
[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"

[language.debugger.templates.args]
program = "{0}"
runInTerminal = true

[[language]]
name = "python"
indent = { tab-width = 4, unit = "4" }
comment-token = "#"

[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "4" }

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "4" }

[[language]]
name = "go"
auto-format = true

[[language]]
name = "arduino"
scope = "source.arduino"
grammar = "c"
language-servers = ["arduino-lsp"]
file-types = ["ino", "arduino"]
roots = []
indent = { tab-width = 4, unit = "4" }

[language-server.arduino-lsp]
command = "arduino-language-server"

[[language]]
name = "hebi"
scope = "source.hebi"
file-types = ["hebi"]
roots = []
comment-token = "#"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "markdown"
language-servers = ["mdpls"]
[language-server.mdpls]
command = "/home/salman/.cargo/bin/mdpls"
config = { markdown.preview.auto = true, markdown.preview.browser = "firefox" }

[[language]]
name = "typescript"
language-id = "typescript"
scope = "source.ts"
injection-regex = "^(ts|typescript)$"
file-types = ["ts"]
shebangs = ["deno"]
roots = ["deno.json", "deno.jsonc", "package.json"]
auto-format = true
language-servers = ["deno-lsp"]

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]

[language-server.deno-lsp.config.deno]
enable = true

[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "scheme"
language-servers = [ "steel-language-server" ]

[language-server.steel-language-server]
command = "steel-language-server"
args = []
