# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "root/root";
    fsType = "zfs";
  };

  fileSystems."/nix" = {
    device = "root/nix";
    fsType = "zfs";
  };

  fileSystems."/var" = {
    device = "root/var";
    fsType = "zfs";
  };

  fileSystems."/home" = {
    device = "root/home";
    fsType = "zfs";
  };

  fileSystems."/efiboot/efi" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077" "X-mount.mkdir" "iocharset=iso8859-1"];
  };

  fileSystems."/mnt/general" = {
    device = "tank/general";
    fsType = "zfs";
  };

  fileSystems."/mnt/ncdata" = {
    device = "tank/ncdata";
    fsType = "zfs";
  };

  fileSystems."/mnt/immich" = {
    device = "tank/immich";
    fsType = "zfs";
  };

  fileSystems."/mnt/jellyfin" = {
    device = "tank/jellyfin";
    fsType = "zfs";
  };

  fileSystems."/mnt/movies" = {
    device = "tank/movies";
    fsType = "zfs";
  };

  fileSystems."/mnt/homepage-dashboard" = {
    device = "tank/homepage-dashboard";
    fsType = "zfs";
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
