#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

#set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill $SCRIPTPATH/background.png
fi

#boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom --config $SCRIPTPATH/picom.config &> /dev/null &
  # picom --experimental-backends --config $SCRIPTPATH/picom.config &> /dev/null &
fi


if type "xrandr"; then 
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar -c $SCRIPTPATH/polybar.config --reload pag &
  done
else 
  polybar -c $SCRIPTPATH/polybar.config --reload pag &
fi
nm-applet &
greenclip daemon &
dunst
# pagbar --config $SCRIPTPATH/pagbar.toml &