#!/usr/bin/env bash

machine=$(echo "$1" | tr -d '[:space:]')

set -e
set -x
alejandra . &> /dev/null
git dft *.nix
echo "Rebuilding NixOS for $machine..."
sudo nixos-rebuild switch --flake ".#$machine" &>nixos-switch.log || (cat "nixos-switch.log" | grep --color error && false)
gen=$(nixos-rebuild list-generations | grep current)
git commit -am "$gen"
