#!/usr/bin/env bash
set -e
set -x

alejandra . &> /dev/null
echo "Rebuilding NixOS for home-server..."
nixos-rebuild switch --use-remote-sudo --build-host localhost --target-host 192.168.0.225 --flake ".#home-server"
